### ISSUE TITLE
Support unnamed attribute values

### ISSUE THREAD

**Issue by ejball** [FacilityApi/Facility#10]
For less typing, it might be nice to support a leading unnamed attribute value, e.g. `[tag(shiny)]` instead of (or as an alternative to) `[tag(name: shiny)]`.

**Comment by ejball** [comment]
Other fun ideas:

```
[http("https://api.example.com/v1/")]
[http("GET /widgets/{id}")]
[obsolete("message")]
[csharp("namespace")]
```

But is it really worth it?

**Comment by ddunkin** [comment]
In some of those examples it's obvious to me what the unnamed value is, some not. Saving the typing isn't worth the ambiguity, IMO. It's not like we're typing up FSDs all day such that saving a few keystrokes adds up to a meaningful time savings. On the other hand, it feels very natural in C#, so maybe someday?

**Comment by ejball** [comment]
I agree; doesn't seem worth it. Closing for now.
