### ISSUE TITLE
Create static method for build scripts

### ISSUE THREAD

**Issue by ejball** [FacilityApi/Facility#18]
We should attach a Cake addin to `Facility.CodeGen.Console`. Something like:

```
FsdGenFsd(File, File/Directory, FsdGenFsdSettings);
```

**Comment by ejball** [comment]
This would be of remarkably little value, at least in this project, especially now that Swagger support has been moved into its own project. But I will add similar issues to the other projects, where they would be more valuable.

**Comment by ejball** [comment]
We could also just make it an easy-to-use static method in the normal C# library.

If we really want to help Cake users, creating a single Cake addin that includes all stable versions of all of the code generators would be a win-win (nicer for clients, simpler to develop and maintain, except for remembering to build and publish every time a generator changes).

**Comment by ejball** [comment]
Not worth the effort.

**Comment by ddunkin** [comment]
Doh, wrong button

**Comment by ejball** [comment]
Fixed in 9612807281de202db96ca708c77fd2df9568a85b.
