### ISSUE TITLE
Support redirect responses

### ISSUE THREAD

**Issue by ddunkin** [FacilityApi/Facility#21]
Sometimes web services return a redirect response. Should FSD be able to model this? Does it apply to transports other than HTTP? What are real-world examples?

**Comment by ejball** [comment]
I'd be interested in use cases. It's not pretty, but this could work as things are:

```
service RedirectApi
{
	[http(method: get, code: 308)]
	method alwaysRedirect
	{
		input: string;
	}:
	{
		[http(from: header, name: Location)]
		redirectTo: string;
	}

	method sometimesRedirect
	{
		input: string;
	}:
	{
		output: string;

		[http(from: body, code: 308)]
		isRedirect: boolean;

		[http(from: header, name: Location)]
		redirectTo: string;
	}
}
```

**Comment by ejball** [comment]
@ddunkin, any more thoughts on this? Barring objection, I will close this issue.

**Comment by ddunkin** [comment]
👍
