### ISSUE TITLE
References/Imports in FSD

### ISSUE THREAD

**Issue by sportnak** [FacilityApi/Facility#35]
I'd like to be able to use references in FSD to share type definitions between services. This would facilitate the definition of smaller subsections of an API. For example, when adding an admin API, it would be beneficial to create a separate FSD file and allow it to reference type definitions used in the original FSD definition. In ChMS, we have a very generic type definition for our record system - so I'd like to add an abstraction layer in order to improve the developer experience with the service. Here's a (slightly simplified) example

ChmsApi.fsd
```
	[http(method: POST, path: "/v1/group/{groupId}/records/{recordKind}/create")]
	method createRecordBatch
	{
		[http(from: header)] authorization: string;

		groupId: int32;
		fieldDatas: RecordFieldData[][];
		metadata: RecordMetadata;
	}:
	{
		results: result<Record>[];
	}
```

CustomFormsApi.fsd
```
	[http(method: POST, path: "/v1/forms/createSubmission")]
	method createSubmission
	{
		[http(from: header)] authorization: string;

		groupId: int32;
		fieldDatas: CustomFormFieldData[][];
		metadata: RecordMetadata;
	}:
	{
		results: result<CustomFormRecord>[];
	}
```

In this example, the inputs and outputs might be typed differently ( `CustomFormFieldData` and `CustomFormRecord` though they might have some overlap, so an `extends` kind of method would also be useful), but the `RecordMetadata` property is something that wouldn't change between the two services. So being able to share that definition rather than having to recreate it would be ideal.

**Comment by ejball** [comment]
The closest thing we currently have to this is support for tags and the ability to exclude elements with a particular tag (e.g. `admin`) when running code generators. That's probably not sufficient to your needs, but I thought I'd mention it.

I'm open to discussing manageable changes to the FSD parser that would help here. But writing a custom preprocessing tool that generates the FSD you want might be the fastest and simplest solution.

**Comment by sportnak** [comment]
I was starting on a pre-processing tool that handled dropping in temporary values and updating references in post, but thought it would be valuable to start the discussion here. 

For changes to the parser, I could use `#include ChmsApi.RecordMetadata` and running through `CustomFormsApi.fsd` would then not throw when no definition is found for `RecordMetadata` instead the generation of the server files should include the import statements for `ChmsApi.RecordMetadata`. A pre/post processing tool might actually be a little more work because I would need to do one of the following:

1. duplicate the definition from one fsd to the other (same definition, but copied) - easier implementation, bad practices
2. create a fake/temp fsd file to run through the codegen tool and then clean it up in post - harder implementation, desired result

I'll probably run through option 2 - unless there's an option that stands out to you as more optimal. I wouldn't mind taking a stab at the FSD parser changes

**Comment by ejball** [comment]
Probably the simplest way to reuse a definition would be a C-style `#include path-to-fsd-fragment.fsf`. We'd just have to swap out the `#include` with the content of the referenced file [before parsing](https://github.com/FacilityApi/Facility/blob/24ad51cce081c8a164ad2dec228d7d66da6d1d14/src/Facility.Definition/CodeGen/FileGenerator.cs#L70). In your example, we'd move `RecordMetadata` to the fragment and include it from both FSDs. A fragment could even just have fields, which could be used to simulate a sort of "extends".

Ideally we would also send along a line number mapping to `ServiceDefinitionText` so that parsing errors could return the correct file name and line number.

An actual "import" feature that could pull in part of an otherwise valid FSD would be potentially nicer but quite a bit more complicated, especially depending on the expectations of code generators, e.g., do they rely on the DTO code generated by the imported FSD or regenerate their own duplicate DTOs?

**Comment by sportnak** [comment]
Yeah your recommendation sounds like option 1 above. Option 2 mainly requires keeping track of the references and creating the imports correctly. I would expect that the DTO code generated by the imported FSD would be the desired result I guess because I wouldn't actually be able to use the shared definition between methods - i.e. `SampleMethod(ChmsApi.RecordMetadata)` wouldn't accept a `CustomForm.RecordMetadata` unless I had some sort of mapper defined.

**Comment by ejball** [comment]
Once upon a time I intended to support true `import`, but [I dropped it](https://git.faithlife.dev/Logos/ServiceFramework/commit/d539f729ac1cee3da30322484799c447c6292e8c) to avoid the complexity. Supporting it, especially with shared DTOs, would impact every code generator. Versioning would get a lot more interesting. I'm not currently inclined to impose that burden on the framework.

**Comment by ejball** [comment]
Closing in favor of #41.
