### ISSUE TITLE
Reject all but the standard HTTP methods for APIs

### ISSUE THREAD

**Issue by ejball** [FacilityApi/Facility#8]
To help catch typos, we should fail on everything but `GET`, `POST`, `PUT`, `DELETE`, and `PATCH`.

**Comment by ddunkin** [comment]
Consider WebDAV verbs also. I've seen those used in REST APIs.

**Comment by ejball** [comment]
Thanks; I don't know much about them. Do you know if they would they make sense for a Facility API, i.e. are they likely to use JSON request/response bodies? My initial investigation suggests not.

**Comment by ddunkin** [comment]
I'm trying to remember where I've seen them, but coming up short. It was probably `COPY` and/or `MOVE`.
